#!/bin/sh
set -e

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage ()
{
    echo "\
Usage: eve [OPTION...] COMMAND [COMMAND-OPTION...]

Eve is meant for system administrators who wants to centralize and
automate system configuration and package installation.

The COMMAND specify the action sequence performed by the tool.
Currently COMMAND may be 'apply'.

Common options:

  -n, --dry-run             do nothing except print what should be done
  -h, --help                show this help text.
  -V, --version             show version information.
  -v, --verbose             Increase verbosity.

The environment variable EVE_CONF_DIR specify the location of a
configuration file (defaults to /etc/eve/eve.conf) which is read
before command line parameters are parsed.

Report bugs to <sysadmin@yubico.com>." 1>&2
}

version ()
{
    echo "\
eve (Eve) 1.0
Copyright (C) 2012 Simon Josefsson
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson."
}

# Read configuration file.
{
    if test -z "$EVE_CONF_DIR"; then
	EVE_CONF_DIR=/etc/eve
    fi

    EVE_CONF="$EVE_CONF_DIR/eve.conf"

    if test -e $EVE_CONF; then
	set -a
	. $EVE_CONF
	set +a
    fi

    export EVE_CONF EVE_CONF_DIR
}

# Command line parsing.
{
    while test $# -gt 0; do
	case "$1" in
	    --dry-run | -n)
		EVE_DRY_RUN=y
		shift ;;
	    --verbose | -v)
		EVE_VERBOSE=y
		shift ;;
	    --help | -h )
		usage
		exit 0 ;;
	    --version | -V )
		version
		exit 0 ;;
	    -- )
        # Stop option processing
		shift
		break ;;
	    -* )
		echo "eve: unknown option $1" 1>&2
		echo "Try 'eve --help' for more information." 1>&2
		exit 1 ;;
	    * )
		break ;;
	esac
    done

    if test $# -eq 0; then
	usage
	exit 0
    fi

    export EVE_VERBOSE EVE_DRY_RUN
}

cmd="$1"
shift

dir="$EVE_CONF_DIR/$cmd.d"

if ! test -d "$dir"; then
    echo "eve: unknown command '$cmd'" 1>&2
    echo "Try 'eve --help' for more information." 1>&2
    exit 1
fi

parts=$(echo `find $dir/ -mindepth 1 -maxdepth 1 \
    -type f -executable -name '[0-9]*' \! -name \*~ | sort -n`)

if test -z "$parts"; then
    echo "eve: nothing to do?!" 1>&2
    exit 1
fi

for part in $parts; do
    test -z "$EVE_VERBOSE" || echo "eve: invoking $part $@"
    "$part" "$@"
done

exit 0
