#!/bin/sh
set -e

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if test -z "$EVE_MODEL"; then	 
    echo "error: model directory not configured" 1>&2
    echo "Try setting EVE_MODEL in $EVE_CONF." 1>&2
    exit 1
fi

if ! test -d "$EVE_MODEL"; then	 
    echo "error: model directory $EVE_MODEL does not exist" 1>&2
    exit 1
fi

if ! test -d "$EVE_MODEL/overlay.d"; then	 
    echo "error: no overlay directory in model directory $EVE_MODEL" 1>&2
    echo "Try setting EVE_MODEL in $EVE_CONF." 1>&2
    exit 1
fi
