#!/bin/sh

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

if test -z "$EVE_MODEL"; then	 
    echo "$self: error: model directory not configured" 1>&2
    echo "$self: Try to set EVE_MODEL in $EVE_CONF." 1>&2
    exit 1
fi

if ! test -d "$EVE_MODEL"; then	 
    echo "$self: error: model directory $EVE_MODEL does not exist" 1>&2
    exit 1
fi

for d in pre-tasks.d delete.d overlay.d post-tasks.d; do
    if ! test -d "$EVE_MODEL/$d"; then
	echo "$self: error: no such directory $EVE_MODEL/$d" 1>&2
	exit 1
    fi
done
