#!/bin/bash

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

# FIXME: How to do -print0 loop without relying on non-POSIX read -d?

cd "$EVE_MODEL/delete" && find . -type f -print0 | (
    while IFS= read -r -d $'\0' file; do
	if test -f /"$file"; then
	    test -z "$EVE_VERBOSE" || echo "$self: Removing '$file'"
	    if test -n "$EVE_DRY_RUN$EVE_DRY_TASKS"; then
		echo "rm -f /\"$file\""
	    else
		rm -f /"$file"
	    fi
	fi
    done
)
