#!/bin/bash

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

if test -n "$DRY_RUN$DRY_TASKS"; then
    dry=echo
else
    dry=
fi

MODEL_DELETE=$EVE_MODEL/delete.d

find $MODEL_DELETE -type f -print0 | (
    while IFS= read -r -d $'\0' file; do
	test -z "$EVE_VERBOSE" || echo "$self: Removing $file"
    done
)
