#!/bin/bash

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

# FIXME: How to do -print0 loop without relying on non-POSIX read -d?

cd "$EVE_MODEL/overlay.d" && find . -type f -print0 | (
    while IFS= read -r -d $'\0' file; do
	dir=`dirname "$file"`
	if ! (cd / && test -d "$dir"); then
	    test -z "$EVE_VERBOSE" || echo "$self: mkdir '$dir'"
	    if test -n "$EVE_DRY_RUN$EVE_DRY_TASKS"; then
		echo "mkdir \"$dir\""
	    else
		cd / && mkdir -p "$dir"
	    fi
	fi
	test -z "$EVE_VERBOSE" || echo "$self: Copying '$file' '$dir'"
	if test -n "$EVE_DRY_RUN$EVE_DRY_TASKS"; then
	    echo "cp $EVE_MODEL/overlay.d/\"$file\"" /\"$dir\"
	else
	    cd / && cp "$EVE_MODEL/overlay.d/$file" "$dir"
	fi
    done
)
