#!/bin/sh

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

MODEL_OVERLAY=$EVE_MODEL/overlay.d
if test -n "$EVE_DRY_RUN"; then
    RSYNC_ARGS="-n $@"
else
    RSYNC_ARGS="$@"
fi

test -z "$EVE_VERBOSE" || echo "$self: Invoking rsync --archive $RSYNC_ARGS $MODEL_OVERLAY/ /"

exec rsync --archive $RSYNC_ARGS $MODEL_OVERLAY/ /
