#!/bin/sh

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

if ! test -d "$COSMOS_REPO/.git"; then
    test -z "$COSMOS_VERBOSE" || \
	echo "$self: ignoring non-git repository: $COSMOS_REPO" 1>&1
    exit 0
fi

if test -n "$COSMOS_VERBOSE"; then
    GIT_ARGS="$GIT_ARGS -v"
else
    GIT_ARGS="$GIT_ARGS -q"
fi

if test -n "$COSMOS_DRY_RUN$COSMOS_DRY_TASKS"; then
    test -z "$COSMOS_VERBOSE" || echo "$self: invoking (dry-run) update"
    echo "cd \"$COSMOS_REPO\" && git pull $GIT_ARGS"
else
    test -z "$COSMOS_VERBOSE" || echo "$self: cloning $repo into $COSMOS_REPO"
    cd "$COSMOS_REPO" && git pull $GIT_ARGS
fi
