#!/bin/sh

# Copyright (C) 2012 Simon Josefsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e
self=`basename $0`

GNUPGHOME="$COSMOS_CONF_DIR/gnupg"
GPG="gpg --homedir $COSMOS_CONF_DIR/gnupg"

if ! test -d $COSMOS_CONF_DIR/gnupg; then
    mkdir -m 700 $COSMOS_CONF_DIR/gnupg
fi

if test -n "$COSMOS_DRY_RUN"; then
    test -z "$COSMOS_VERBOSE" || echo "$self: invoking gpg (dry-run)"
    echo "$GPG $@"
elif test -n "$COSMOS_DRY_TASKS"; then
    test -z "$COSMOS_VERBOSE" || echo "$self: invoking (dry-tasks) $GPG --dry-run $@"
    $GPG --dry-run "$@"
else
    test -z "$COSMOS_VERBOSE" || echo "$self: invoking $GPG $@"
    $GPG "$@"
fi
